In [1]:
%load_ext autoreload
%autoreload 2
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from constants import *
from glob import glob
from datetime import datetime
import os

df_prazniki = pd.read_csv(DATA_PRAZNIKI, sep=';', encoding='UTF-8')
df_prazniki.columns = df_prazniki.columns.str.lower()
df_prazniki['datum'] = pd.to_datetime(df_prazniki['datum'], format='%d.%m.%Y')

# keep only datum, dela_prost_dan
df_prazniki = df_prazniki[['datum', 'dela_prost_dan']]

# take only 2022, 2023, 2024
df_prazniki = df_prazniki[df_prazniki['datum'].dt.year >= 2022]
df_prazniki = df_prazniki[df_prazniki['datum'].dt.year <= 2024]

# strip and map da ne to True False
df_prazniki['dela_prost_dan'] = df_prazniki['dela_prost_dan'].str.strip()
assert df_prazniki['dela_prost_dan'].unique().shape[0] == 2, f"unique = {df_prazniki['dela_prost_dan'].unique()}"
df_prazniki['dela_prost_dan'] = df_prazniki['dela_prost_dan'].map({'da': True, 'ne': False})

# sort by datum
df_prazniki = df_prazniki.sort_values(by=['datum'])

# save to csv
df_prazniki.to_csv(OUT_PRAZNIKI, index=False)

df_prazniki = pd.read_csv(OUT_PRAZNIKI)
df_prazniki

         datum  dela_prost_dan
0   2022-01-01            True
1   2022-01-02            True
2   2022-02-08            True
3   2022-04-17            True
4   2022-04-18            True
5   2022-04-27            True
6   2022-05-01            True
7   2022-05-02            True
8   2022-06-05            True
9   2022-06-08           False
10  2022-06-25            True
11  2022-08-15            True
12  2022-08-17           False
13  2022-09-15           False
14  2022-10-25           False
15  2022-10-31            True
16  2022-11-01            True
17  2022-11-23           False
18  2022-12-25            True
19  2022-12-26            True
20  2023-01-01            True
21  2023-01-02            True
22  2023-02-08            True
23  2023-04-09            True
24  2023-04-10            True
25  2023-04-27            True
26  2023-05-01            True
27  2023-05-02            True
28  2023-05-28            True
29  2023-06-08           False
30  2023-06-25            True
31  2023-08-15            True
32  2023-08-17           False
33  2023-09-15           False
34  2023-10-25           False
35  2023-10-31            True
36  2023-11-01            True
37  2023-11-23           False
38  2023-12-25            True
39  2023-12-26            True
40  2024-01-01            True
41  2024-01-02            True
42  2024-02-08            True
43  2024-03-31            True
44  2024-04-01            True
45  2024-04-27            True
46  2024-05-01            True
47  2024-05-02            True
48  2024-05-19            True
49  2024-06-08           False
50  2024-06-25            True
51  2024-08-15            True
52  2024-08-17           False
53  2024-09-15           False
54  2024-10-25           False
55  2024-10-31            True
56  2024-11-01            True
57  2024-11-23           False
58  2024-12-25            True
59  2024-12-26            True